server:
  port: 7777

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: http://51.250.102.12:8081
          predicates:
            - Path=/*/*/*/orders, /*/*/*/orders/**
        - id: user-info-service-route
          uri: http://51.250.102.12:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/search, /*/*/*/users/signup
        - id: product-service-route
          uri: http://51.250.102.12:9090
          predicates:
            - Path=/*/*/*/products/{externalId}
            - Path=/*/*/*/products/special-prices/{specialPriceExternalId}
            - Path=/*/*/*/products/characteristics/{characteristicExternalId} 
            - Path=/*/*/*/products/{sellerId}
            - Path=/*/*/*/products/special-prices/{productExternalId}
            - Path=/*/*/*/products/images/{productId}
            - Path=/*/*/*/product-previews
            - Path=/*/*/*/sellers/{sellerId}/products/{productId}/price
            - Path=/*/*/*/sellers/{sellerId}/products/visibility
            - Path=/*/*/*/sellers/{sellerId}/products/archive
            - Path=/*/*/*/sellers/{sellerId}/products
            - Path=/*/*/*/sellers/{sellerId}/archived-products
            - Path=/*/*/*/types/{typeId}
            - Path=/*/*/*/special-prices/{specialPriceId}
            - Path=/*/*/*/images
        - id: seller-service-route
          uri: http://51.250.102.12:8085
          predicates:
            - Path=/*/*/*/sellers, /*/*/*/sellers/{externalId}
        - id: favorite-service-route
          uri: http://51.250.102.12:8082
          predicates:
            - Path=/*/*/*/*/*/favorites, /*/*/*/*/*/favorites/{externalId}
        - id: upload-service-route
          uri: http://51.250.102.12:9001
          predicates:
              - Path=/*/*/*/upload, /*/*/*/download, /*/*/*/url, /*/*/*/delete, /*/*/*/urls
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://51.250.102.12:7777/login/oauth2/code/custom-oidc"
        provider:
          custom-oidc:
            issuer-uri: "http://51.250.102.12:9000"
            token-uri: "http://51.250.102.12:9000/oauth2/token"
            authorization-uri: "http://51.250.102.12:9000/oauth2/authorize"
            jwk-set-uri: "http://51.250.102.12:9000/oauth2/jwks"
            user-info-uri: "http://51.250.102.12:9000/userinfo"