server:
  port: 7777

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: order-service-route
          uri: http://51.250.102.12:8081
          predicates:
            - Path=/*/*/*/orders, /*/*/*/orders/**
        - id: user-service-route
          uri: http://51.250.102.12:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{externalId}, /*/*/*/users/search, /*/*/*/users/signup
        - id: product-service-route
          uri: http://51.250.102.12:9090
          predicates:
            - Path=/*/*/*/products, /*/*/*/products/{externalId}, /*/*/*/products/search, /*/*/*/*/*/products, /*/*/*/*/*/products/categories, /*/*/*/*/*/products/categories/**, /*/*/*/*/*/products/search/by-name
        - id: favorite-service-route
          uri: http://51.250.102.12:8082
          predicates:
            - Path=/*/*/*/*/*/favorites, /*/*/*/*/*/favorites/{externalId}
        - id: upload-service-route
          uri: http://51.250.102.12:9001
          predicates:
              - Path=/*/*/*/upload, /*/*/*/download, /*/*/*/url, /*/*/*/delete, /*/*/*/urls
      default-filters:
        - AuthFilter

  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://51.250.102.12:7777/login/oauth2/code/custom-oidc"
        provider:
          custom-oidc:
            issuer-uri: "http://51.250.102.12:9000"
            token-uri: "http://51.250.102.12:9000/oauth2/token"
            authorization-uri: "http://51.250.102.12:9000/oauth2/authorize"
            jwk-set-uri: "http://51.250.102.12:9000/oauth2/jwks"
            user-info-uri: "http://51.250.102.12:9000/userinfo"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

application:
  security:
    white-list:
      # users-api
      - url: /*/*/*/users/signup
        methods:
          - POST
      # products-api
      - url: /*/*/*/products/{externalId}
        methods:
          - GET
      - url: /*/*/*/products
        methods:
          - GET
      - url: /*/*/*/products/search
        methods:
          - GET
      - url: /*/*/*/*/*/products/categories
        methods:
          - GET
      - url: /*/*/*/*/*/products/categories/**
        methods:
          - GET
      - url: /*/*/*/*/*/products/search/by-name
        methods:
          - GET

logging:
  level:
    org: INFO