server:
  port: 7777

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: http://172.17.0.1:8081
          predicates:
            - Path=/*/*/*/orders, /*/*/*/orders/**
        - id: user-service-route
          uri: http://172.17.0.1:8080
          predicates:
            - Path=/*/*/*/users, /*/*/*/users/{userId}
        - id: seller-service-route
          uri: http://172.17.0.1:8085
          predicates:
            - Path=/*/*/*/sellers, /*/*/*/sellers/{sellerId}
        - id: product-service-route
          uri: http://51.250.102.12:9090
          predicates:
            - Path=/*/*/*/types, /*/*/*/types/{typeId}, /*/*/*/types/{typeId}/rooms, /*/*/*/rooms, /*/*/*/rooms/{roomId}, /*/*/*/rooms/{roomId}/types, /*/*/*/product-previews, */*/*/*/*/products, /*/*/*/*/*/products/categories, /*/*/*/*/*/products/categories/**, /*/*/*/*/*/products/search/by-name, /*/*/*/*/{sellerId}/products, /*/*/*/*/{sellerId}/products/**, /*/*/*/*/{sellerId}/products/{productId}, /*/*/*/*/{sellerId}/products/{productId}/**, /*/*/*/*/{sellerId}/products/special-prices/{specialPriceId}, /*/*/*/*/{sellerId}/products/characteristics/{characteristicId}, /*/*/*/*/{sellerId}/archive/products
        - id: favorite-service-route
          uri: http://172.17.0.1:8082
          predicates:
            - Path=/*/*/*/*/*/favorites, /*/*/*/*/*/favorites/{externalId}
        - id: upload-service-route
          uri: http://172.17.0.1:9001
          predicates:
              - Path=/*/*/*/upload, /*/*/*/download, /*/*/*/url, /*/*/*/delete, /*/*/*/urls
      default-filters:
        - AuthFilter

  security:
    oauth2:
      client:
        registration:
          custom-oidc:
            provider: custom-oidc
            scope: openid
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://172.17.0.1:7777/login/oauth2/code/custom-oidc"
        provider:
          custom-oidc:
            issuer-uri: "http://172.17.0.1:9000"
            token-uri: "http://172.17.0.1:9000/oauth2/token"
            authorization-uri: "http://172.17.0.1:9000/oauth2/authorize"
            jwk-set-uri: "http://172.17.0.1:9000/oauth2/jwks"
            user-info-uri: "http://172.17.0.1:9000/userinfo"

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, loggers

application:
  security:
    white-list:
      # users-api
      - url: /*/*/*/users
        methods: POST
      # seller-api  
      - url: /*/*/*/sellers
        methods: POST
      # products-api
#      - url: /*/*/*/products/{externalId}
#        methods: GET
#      - url: /*/*/*/products/{productId}
#        methods: GET
      - url: /*/*/*/types
        methods: GET
      - url: /*/*/*/types/{typeId}
        methods: GET
      - url: /*/*/*/rooms/{roomId}/types
        methods: GET
      - url: /*/*/*/rooms
        methods: GET
      - url: /*/*/*/rooms/{roomId}
        methods: GET
      - url: /*/*/*/types/{typeId}/rooms
        methods: GET
      - url: /*/*/*/product-previews
        methods: POST, GET  
    

logging:
  level:
    org: INFO
