server:
  port: 9000

spring:
  application:
    name: authorization-server

app:
  security:
    client-settings:
      client-id: client
      client-secret: "{noop}secret"
      redirect-login-uri: "http://51.250.102.12:7777/login/oauth2/code/custom-oidc"
      redirect-success-login-uri: "http://51.250.102.12:7777/authorized"
      scope: read
    token-settings:
      access-token-life-time-in-minutes: 10080 # 7 days
      refresh-token-lifetime-in-minutes: 11520 # 8 days
    user-data-provider-url: "http://172.17.0.1:8080/private/api/v1"
    seller-data-provider-url: "http://172.17.0.1:8085/private/api/v1"

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8010
    ssl:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://158.160.27.104:9411/api/v2/spans

logging:
  level:
    org.springframework: DEBUG