server:
  port: 8083

spring:
  application:
    name: favorites-service
    url: /public/api/v1/users/

  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    enabled: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  datasource:
    url: jdbc:postgresql://158.160.27.104:5432/favorite_db
    username: user
    password: password
    driverClassName: org.postgresql.Driver

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8003
    ssl:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://158.160.27.104:9411/api/v2/spans