server:
  port: 9090

spring:
  application:
    name: product-service
  flyway:
    enabled: false
  app:
    product:
      url: /public/api/v1/products/
    seller:
      url: /public/api/v1/sellers/

  kafka:
    bootstrap-servers: 172.17.0.1:9092

  datasource:
    url: jdbc:postgresql://158.160.27.104:5432/product_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      jedis:
        pool:
          enabled: false
      host: 51.250.102.12
      port: 6379
      database: 0