server:
  port: 8082

spring:
  application:
    name: review-service
    url: /public/api/v1
  flyway:
    enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://158.160.27.104:5432/review_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true