server:
  port: 8085

spring:
  application:
    name: seller-info-service
    url: /public/api/v1/sellers
  flyway:
    enabled: false

  datasource:
    url: jdbc:postgresql://158.160.27.104:5432/seller_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update # далее validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://172.17.0.1:9000/oauth2/jwks

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8005
    ssl:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://158.160.27.104:9411/api/v2/spans