server:
  port: 9001

application:
  extension:
    jpg:
      max_file_size_in_bytes: 153600
    png:
      max_file_size_in_bytes: 1000000
    pdf:
      max_file_size_in_bytes: 50000
  validation:
    maximum_files_count: 5
  object-storage:
    host: storage.yandexcloud.net
    region: ru-central1
    bucket-name: marketplace-object-storage
    credentials:
      secret-key: ${SECRET_KEY}
      access-key: ${ACCESS_KEY}
    expiration-time: 60 # in minutes

spring:
  application:
    name: upload-service
  data:
    mongodb:
      uri: mongodb://158.160.27.104:27017/upload-service
      database: upload-service

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8030
    ssl:
      enabled: false
  zipkin:
    tracing:
      endpoint: http://158.160.27.104:9411/api/v2/spans

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG